// Email image URLs from Supabase storage
// Auto-generated by upload-email-images.ts script

export const EMAIL_IMAGES = {
  LOGO: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/logo.svg',
  HERO: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/hero.png',
  DISCOVER: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/discover.png',
  ORGANIZE: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/organize.png',
  SHARE: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/share.png',
  REFERRAL: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/referral.png'
} as const;
