// Email image URLs from Supabase storage
// Auto-generated by upload-email-images.ts script

export const EMAIL_IMAGES = {
  // LOGO: SVG not supported in emails, using text logo instead
  HERO: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/hero.png',
  DISCOVER: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/discover.png',
  ORGANIZE: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/organize.png',
  SHARE: 'https://cvkqgduefcvkeagfvvgr.supabase.co/storage/v1/object/public/email-assets/share.png'
  // REFERRAL: Removed - not using referral functionality
} as const;

// Text logo configuration for email compatibility
export const EMAIL_LOGO = {
  TEXT: 'Narra',
  STYLES: {
    fontSize: '36px',
    fontWeight: 'bold',
    color: '#000000',
    fontFamily: '"Fira Sans", "Lucida Sans Unicode", "Lucida Grande", sans-serif',
    textAlign: 'center' as const,
    margin: '0',
    padding: '20px 0',
    letterSpacing: '-1px'
  }
} as const;
